
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 07 23:21:38 CST 2018
//----------------------------------------------------

package compiladorfinal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int rimprimir = 19;
  public static final int cadena = 18;
  public static final int rmientras = 20;
  public static final int relse = 22;
  public static final int decimal = 16;
  public static final int menque = 7;
  public static final int or = 14;
  public static final int llavizq = 5;
  public static final int mayque = 8;
  public static final int llavder = 6;
  public static final int bool = 17;
  public static final int ptcoma = 2;
  public static final int EOF = 0;
  public static final int rif = 21;
  public static final int cigual = 11;
  public static final int error = 1;
  public static final int mayoigual = 10;
  public static final int parizq = 3;
  public static final int entero = 15;
  public static final int parder = 4;
  public static final int diferente = 12;
  public static final int menoigual = 9;
  public static final int and = 13;
  public static final int identificador = 23;
}

